# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

before_install:
- Rscript -e 'install.packages("devtools")'
- Rscript -e 'devtools::install_deps(dep = TRUE, auth_token = GITHUB_PAT)'
